class_name FelipeNames
extends Node

const nomes: Array[String] = [
	"Felipe Díogenes Pirâmides",
	"Felipe Dias Pinto",
	"Felipe da Ponta",
	"Felipe Dantas Pereira",
	"Felipe Diego Pavuna",
	"Felipe da Ponta",
	"Felipe Dantas Pereira",
	"Felipe Diego Pavuna",
	"Felipe Duarte Ponta",
	"Felipe da Porta",
	"Felipe Damas Pinheiro",
	"Felipe de Paula",
	"Felipe Davi Pimentel",
	"Felipe do Porto",
	"Felipe Dolores Peixoto",
	"Felipe Damásio Padilha",
	"Felipe Delgado Pacheco",
	"Felipe Demétrio Paschoal",
	"Felipe Dionísio Peixe",
	"Felipe Desgraça Porcaria",
	"Felipe Dinossauro Pêssego",
	"Felipe Dado Postura",
	"Felipe Duas Parábolas",
	"Felipe Digimon Putarias",
	"Felipe Drummond Pitágoras",
	"Felipe Dorres Pêmeas",
	"Felipe Dinheiro Passaporte",
	"Felipe Dádivas Presidenciais",
	"Felipe Dametucosita Parangolé",
	"Felipe Ditadura Parangaba",
	"Felipe Djongs Plongs",
	"Felipe Dura Pitomba",
	"Felipe Dicas Pterodáctilas",
	"Felipe Dumativa Pagameujogo",
	"Felipe Dançagatinhodança Porfavor",
	"Felipe D'ávila Portela",
	"Felipe Duna Parte2",
	"Felipe Delipe Pelipe",
	"Felipe Domínio Público",
	"Felipe Danganron Pa",
	"Felipe Décimo Perceiro",
	"Felipe Documentos Proibidos",
	"Felipe Descafeinado Piracanjuba",
	"Felipe Deslocamento Profissional",
	"Felipe Desemborca Pindamonhangaba",
	"Felipe Derivada Parcial",
	"Felipe Desafios Piracicaba",
	"Felipe Dondoca Pirocóptero",
	"Felipe de Portuguesa",
	"Felipe de Pepperoni",
	"F      D      P",
]
