name: Export Game

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: nu {0}

env:
  project-godot-root: ./source/
  itch-project-slug: username/game

jobs:
  export:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip!')"
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: hustcer/setup-nu@v3
        with:
          version: "*"
          enable-plugins: true

      - name: Get Info
        id: info
        run: |
          let version = (open ($env.project-godot-root | path join "project.godot")
            | lines
            | where ($it | str starts-with 'config/version=')
            | first
            | split row '='
            | get 1
            | str trim -c '"')

          $"version=($version)" | save -a $env.GITHUB_OUTPUT

      - name: export game
        id: export
        uses: firebelley/godot-export@v7.0.0
        with:
          godot_executable_download_url: https://downloads.godotengine.org/?version=4.6.1&flavor=stable&slug=linux.x86_64.zip&platform=linux.64
          godot_export_templates_download_url: https://downloads.godotengine.org/?version=4.6.1&flavor=stable&slug=export_templates.tpz&platform=templates
          cache: true
          relative_project_path: ${{ env.project-godot-root }}
          archive_output: true

      - name: create release
        uses: ncipollo/release-action@v1.20.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          tag: ${{ steps.info.outputs.version }}
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: ${{ steps.export.outputs.archive_directory }}/*

      - name: Setup buttler
        uses: remarkablegames/setup-butler@v2
        with:
          butler-version: LATEST

      - name: Upload to Itch
        if: env.itch-project-slug != 'username/game'
        run: echo (ls ${{ steps.export.outputs.archive_directory }}/)
